"""Create initial project tables

Revision ID: b600d0d6c424
Revises: 
Create Date: 2025-09-17 22:25:07.467181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b600d0d6c424'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_question_types_id'), 'question_types', ['id'], unique=False)
    op.create_index(op.f('ix_question_types_slug'), 'question_types', ['slug'], unique=True)
    op.create_table('practice_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passage', sa.Text(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('question_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_questions_id'), 'practice_questions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_questions_id'), table_name='practice_questions')
    op.drop_table('practice_questions')
    op.drop_index(op.f('ix_question_types_slug'), table_name='question_types')
    op.drop_index(op.f('ix_question_types_id'), table_name='question_types')
    op.drop_table('question_types')
    # ### end Alembic commands ###
