"""Consolidate ReadingPassage for both test and practice modes

Revision ID: c47be6a356df
Revises: c0c6f06350b8
Create Date: 2025-09-19 22:14:29.934872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c47be6a356df'
down_revision: Union[str, Sequence[str], None] = 'c0c6f06350b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_questions', sa.Column('passage_id', sa.Integer(), nullable=False))
    op.add_column('practice_questions', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'practice_questions', 'reading_passages', ['passage_id'], ['id'])
    op.drop_column('practice_questions', 'passage')
    op.add_column('reading_passages', sa.Column('title', sa.String(), nullable=True))
    op.add_column('reading_passages', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('reading_passages', 'passage_text')
    op.drop_column('reading_passages', 'order_in_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_passages', sa.Column('order_in_test', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reading_passages', sa.Column('passage_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('reading_passages', 'content')
    op.drop_column('reading_passages', 'title')
    op.add_column('practice_questions', sa.Column('passage', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'practice_questions', type_='foreignkey')
    op.drop_column('practice_questions', 'options')
    op.drop_column('practice_questions', 'passage_id')
    # ### end Alembic commands ###
